config/routes.rb
Rails.application.routes.draw do

  constraints domain: 'podychevo.ru' do
    scope module: 'farm', as: 'farm' do
      get 'about', to: 'about#show'
      resource :order, only: [:create]
      resource :cart, only: [:show, :update, :create]
      get 'search(/page/:page)', to: 'search#index', as: 'search'
      resources :products, only: [:show]
      root 'welcome#index'
    end
  end

  constraints host: '192.168.1.6', port: '3000' do
    resources :trees
    resources :products
    resources :uploads
    root 'products#index'
  end

end

app/models/tree.rb
class Tree < ApplicationRecord
  has_closure_tree order: 'sort_order'
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy]

  # GET /trees
  # GET /trees.json
  def index
    @trees = if params[:id]
                    @tree = Tree.find(params[:id])
                    @tree.children
                  else
                    Tree.roots
                  end
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree.destroy
    respond_to do |format|
      format.html { redirect_to trees_url, notice: 'Tree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_params
      params.require(:tree).permit!#(:es_index, :es_type, :es_body, :parent_id)
    end
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/trees/_form.html.erb
<div id="jsoneditor" style="width: 600px; height: 400px;"></div>
<br />
<div class="form-group">
  <label>es_index</label>
  <input type="text" class="form-control" id="es_index" value="<%= tree.es_index %>">
</div>
<div class="form-group">
  <label>es_type</label>
  <input type="text" class="form-control" id="es_type" value="<%= tree.es_type %>">
</div>
<div class="form-group">
  <label>parent_id</label>
  <input type="text" class="form-control" id="parent_id" value="<%= tree.parent_id %>">
</div>
<div class="form-group">
  <label>sort_order</label>
  <input type="text" class="form-control" id="sort_order" value="<%= tree.sort_order %>">
</div>
<div id="formresult"></div>
<br />
<button class="btn btn-primary" id="sendJSON">Send JSON</button>
<br />
<br />

<script>
  // create the editor
  var container = document.getElementById("jsoneditor");

  var options = {
    mode: 'tree',
    modes: ['code', 'form', 'text', 'tree', 'view'], // allowed modes
    onError: function (err) {
      alert(err.toString());
    },
    onModeChange: function (newMode, oldMode) {
      console.log('Mode switched from', oldMode, 'to', newMode);
    }
  };

  var editor = new JSONEditor(container, options);
  var es_body = <%= tree.es_body.to_json.html_safe %>;
  editor.set(es_body);

  var makeRequest = function(done){
    var xhr = new XMLHttpRequest();
    xhr.open('<%= tree.persisted? ? 'PUT' : 'POST' %>', '<%= polymorphic_path(tree, {format: 'json'}) %>', true);
    xhr.setRequestHeader('content-type', 'application/json');
    xhr.setRequestHeader('accept', 'application/json');

    xhr.onload = function () {
      done(null, xhr.response);
    };

    xhr.onerror = function () {
      done(xhr.response);
    };

    // get json
    var es_body = editor.get();
    var es_index = document.querySelector('#es_index').value;
    var es_type = document.querySelector('#es_type').value;
    var parent_id = document.querySelector('#parent_id').value;
    var sort_order = document.querySelector('#sort_order').value;
    xhr.send(JSON.stringify({tree: {es_index: es_index, es_type: es_type, es_body: es_body, parent_id: parent_id, sort_order: sort_order}}));
  };

  $('#sendJSON').on("click", function(){
    makeRequest(function(err, response){
      if (err) { throw err; }
      $('#formresult').html(response);
    })
  });


</script>

<% if false %>
<%= form_for(tree) do |f| %>
  <% if tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
      <% tree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :es_index %>
    <%= f.text_field :es_index %>
  </div>

  <div class="field">
    <%= f.label :es_type %>
    <%= f.text_field :es_type %>
  </div>

  <div class="field">
    <%= f.label :es_body %>
    <%= f.text_field :es_body %>
  </div>

  <div class="field">
    <%= f.label :parent_id %>
    <%= f.number_field :parent_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% end %>

app/views/trees/edit.html.erb
<h1>Editing Tree</h1>

<%= render 'form', tree: @tree %>

<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<h1>Trees</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Es index</th>
      <th>Es type</th>
      <th>Es body</th>
      <th>Parent</th>
      <th>Sort order</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td><%= tree.id %></td>
        <td><%= tree.es_index %></td>
        <td><%= tree.es_type %></td>
        <td><%= tree.es_body %></td>
        <td><%= tree.parent_id %></td>
        <td><%= tree.sort_order %></td>
        <td><%= link_to_unless tree.leaf?, 'Index', trees_path(id: tree) %></td>
        <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
        <td><%= link_to 'Destroy', tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tree', new_tree_path %>

<% if @tree %>
  <%= link_to 'Back', trees_path(id: @tree.parent) %>
<% end %>

app/views/trees/new.html.erb
<h1>New Tree</h1>

<%= render 'form', tree: @tree %>

<%= link_to 'Back', trees_path %>