config/routes.rb
Rails.application.routes.draw do

  constraints domain: 'podychevo.ru' do
    scope module: 'farm', as: 'farm' do
      get 'about', to: 'about#show'
      resource :order, only: [:create]
      resource :cart, only: [:show, :update, :create]
      get 'search(/page/:page)', to: 'search#index', as: 'search'
      resources :products, only: [:show]
      root 'welcome#index'
    end
  end

  constraints host: '192.168.1.6', port: '3000' do
    resources :trees
    resources :products
    resources :uploads
    root 'products#index'
  end

end

app/controllers/farm/_animals_controller.rb
class Farm::AnimalsController < Farm::ApplicationController

  PER_PAGE = 15

  def show
    @animal = animals_root.children.where("es_body ->> 'title' = ?", params[:id]).first

    body = {
      aggregations: {
        category_ids: {
          terms: {
            field: "category_ids"
          }
        },
        animal_ids: {
          terms: {
            field: "animal_ids"
          }
        }
      },
      query: {
        bool: {
          filter: {
            term: {
              animal_ids: @animal.id
            }
          }
        }
      }
    }

    page = params.fetch(:page, '1').to_i - 1
    result = $client.search({index: 'farm', body: body, size: PER_PAGE, from: page * PER_PAGE})

    @category_ids_buckets = result['aggregations']['category_ids']['buckets']
    @animal_ids_buckets = result['aggregations']['animal_ids']['buckets']

    @products = Kaminari.paginate_array(result['hits']['hits'], total_count: result['hits']['total']).page(params[:page]).per(PER_PAGE)
    render 'search/index'
  end
end

app/controllers/farm/_categories_controller.rb
#class Farm::CategoriesController < Farm::ApplicationController
#
#  PER_PAGE = 15
#  TREE_INDEX = 'farm'
#  TREE_TYPE = 'categories'
#
#  def show
#    @category = categories_root.children.where("es_body ->> 'title' = ?", params[:id]).first
#
#    body = {
#      aggregations: {
#        category_ids: {
#          terms: {
#            field: "category_ids"
#          }
#        },
#        animal_ids: {
#          filter: {
#            term: {
#              category_ids: @category.id
#            }
#          },
#          aggregations: {
#            animal_ids: {
#              terms: {
#                field: "animal_ids"
#              }
#            }
#          }
#        }
#      },
#      filter: {
#        term: {
#          category_ids: @category.id
#        }
#      }
#    }
#
#    if params[:title].present?
#      body.deep_merge!({
#        query: {
#          bool: {
#            must: {
#              match: {title: params[:title]}
#            }
#          }
#        }
#      })
#    end
#
#    page = params.fetch(:page, '1').to_i - 1
#    result = $client.search({index: 'farm', body: body, size: PER_PAGE, from: page * PER_PAGE})
#
#    @category_ids_buckets = result['aggregations']['category_ids']['buckets']
#    @animal_ids_buckets = result['aggregations']['animal_ids']['animal_ids']['buckets']
#
#    @products = Kaminari.paginate_array(result['hits']['hits'], total_count: result['hits']['total']).page(params[:page]).per(PER_PAGE)
#    render 'search/index'
#  end
#end

app/controllers/farm/about_controller.rb
class Farm::AboutController < Farm::ApplicationController
end

app/controllers/farm/application_controller.rb
class Farm::ApplicationController < ApplicationController
  prepend_view_path 'app/views/farm'
  helper_method :categories_root, :options_root, :farm_products_in_cart, :farm_product_in_cart?, :farm_total_cost_of_products_in_cart

  private
  
  def categories_root
    Tree.roots.where(es_index: 'farm', es_type: 'category_ids').first
  end

  def options_root(option_title)
    Tree.roots.where(es_index: 'farm', es_type: option_title).first
  end

  def farm_products
    Product.where(es_index: 'farm', es_type: 'products')
  end

  def farm_products_in_cart
    if session['cart_product_hashes']
      farm_products.where(id: session['cart_product_hashes'].keys)
    else
      farm_products.none
    end
  end

  def farm_product_in_cart?(id)
    session[:cart_product_hashes] && session[:cart_product_hashes].key?(id.to_s)
  end

  def farm_total_cost_of_products_in_cart
    farm_products_in_cart.sum do |product|
      product.es_body['price'] * session['cart_product_hashes'][product.id.to_s]
    end
  end

end

app/controllers/farm/carts_controller.rb
class Farm::CartsController < Farm::ApplicationController
  def create
    product_id = params[:product_id]
    (session['cart_product_hashes'] ||= {}).tap do |cph|
      if cph.key? product_id
        cph[product_id] += 1
      else
        cph[product_id] = 1
      end
    end
  end

  def update

    product_id = params[:product_id]
    count = params[:count].to_i

    if count <= 0
      session['cart_product_hashes'].delete(product_id)
    else
      session['cart_product_hashes'][product_id] = count
      @sum =  params[:count].to_i * Product.find(product_id).es_body['price']
      @products = farm_products_in_cart
    end

    respond_to do |format|
      format.json
    end

  end

  def show
    @products = farm_products_in_cart
    @order = Farm::Order.new
    if @products.exists?
      render 'show'
    else
      render 'empty'
    end
  end

end

app/controllers/farm/orders_controller.rb
class Farm::OrdersController < Farm::ApplicationController

  def create
    @order = Farm::Order.new(order_params)
    if @order.valid?
      @products = farm_products_in_cart
      @session_hash = session.to_hash
      @farm_total_cost_of_products_in_cart = farm_total_cost_of_products_in_cart
      Farm::SellerMailer.order_email(@products, @order, @session_hash, @farm_total_cost_of_products_in_cart).deliver_now
      Farm::BuyerMailer.order_email(@products, @order, @session_hash, @farm_total_cost_of_products_in_cart).deliver_now
      respond_to do |format|
        format.js {render 'create_success'}
      end
      session.delete 'cart_product_hashes'
    else 
      respond_to do |format|
        format.js {render 'create_fail'}
      end
    end
  end

  private

  def order_params
    params.require(:farm_order).permit(:name, :phone, :address, :email)
  end

end

app/controllers/farm/products_controller.rb
class Farm::ProductsController < Farm::ApplicationController

  before_action :history_routines

  def show

    @product = Product.find(params[:id])

    fill_breadcrumbs()

    #if @product.es_body['animal_ids']
    #  @animals = animals_root.children.find(@product.es_body['animal_ids'])
    #end

    body = {
      aggregations: {
        category_ids: {
          terms: {
            field: "category_ids",
            size: 100
          }
        }
      }
    }

    result = $client.search({index: 'farm', body: body})
    @category_ids_buckets = result['aggregations']['category_ids']['buckets']
  end

  private

  def history_routines
    session['history_product_ids'] ||= []
    session['history_product_ids'] |= [params[:id]]
    session['history_product_ids'] = session['history_product_ids'].last(30)
    @history_products = farm_products.where(id: session['history_product_ids'])
  end

  def fill_breadcrumbs
    category_ids = @product.es_body['category_ids']
    @breadcrumbs = []
    leaves = Tree.leaves.with_ancestor(categories_root).where(id: @product.es_body['category_ids'])
    leaves.each do |leaf|
      @breadcrumbs << leaf.self_and_ancestors.reverse_order
    end

    if session[:category_id]
      @breadcrumbs.each_with_index do |breadcrumb, index|
        if breadcrumb.map{|b| b.id}.include? session[:category_id]
          primary = @breadcrumbs.delete_at(index)
          @breadcrumbs.unshift primary
          break
        end
      end
    end
  end
end

app/controllers/farm/search_controller.rb
class Farm::SearchController < Farm::ApplicationController

  before_action :store_location

  PER_PAGE = 18

  def index

    if params[:category_id]
      @category = Tree.find(params[:category_id])
    else
      @category = categories_root
    end

    store_category_id()

    @option_titles = @category.es_body['options']

    if @option_titles
      @option_values = {}
      @option_titles.each do |option_title|
        if params[option_title]
          @option_values[option_title] = Tree.find(params[option_title])
        end
      end
    end

    if params[:min_price]
      @min_price = params[:min_price].to_i
    end

    if params[:max_price]
      @max_price = params[:max_price].to_i
    end

    body = {
      aggregations: {
        max_price: {
          filter: {},
          aggregations: {
            max_price: {
              max: { 
                field: "price" 
              }
            }
          }
        },
        min_price: {
          filter: {},
          aggregations: {
            min_price: {
              min: { 
                field: "price" 
              }
            }
          }
        },
        category_ids: {
          filter: {},
          aggregations: {
            category_ids: {
              terms: {
                field: "category_ids",
                size: 100
              }
            }
          }
        }
      }
    }

    @option_titles.each do |option_title|
      body[:aggregations][option_title] = {
        filter: {},
        aggregations: {
          option_title => {
            terms: {
              field: "properties.#{option_title}",
              size: 100
            }
          }
        }
      }
    end if @option_titles

    @option_titles.each do |option_title|

      if @option_values[option_title]

        add_filters_for_aggregations(body, :category_ids,
          terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })

        add_filters_for_aggregations(body, :min_price,
          terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })

        add_filters_for_aggregations(body, :max_price,
          terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })

        other_option_titles = @option_titles - [option_title]

        other_option_titles.each do |other_option_title|
          add_filters_for_aggregations(body, other_option_title,
            terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })
        end if other_option_titles

        add_post_filters(body,
          terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })

      end


    end if @option_titles

    if @category

      add_filters_for_aggregations(body, :min_price,
        term: { category_ids: @category.id })

      add_filters_for_aggregations(body, :max_price,
        term: { category_ids: @category.id })

      @option_titles.each do |option_title|
        add_filters_for_aggregations(body, option_title,
          term: { category_ids: @category.id })
      end if @option_titles

      add_post_filters(body,
        term: { category_ids: @category.id })
    end

    if @min_price

      add_filters_for_aggregations(body, :category_ids,
        range: { price: { gte: @min_price }})

      @option_titles.each do |option_title|
        add_filters_for_aggregations(body, option_title,
          range: { price: { gte: @min_price }})
      end if @option_titles

      add_post_filters(body,
        range: { price: { gte: @min_price }})
    end

    if @max_price

      add_filters_for_aggregations(body, :category_ids,
        range: { price: { lte: @max_price }})

      @option_titles.each do |option_title|
        add_filters_for_aggregations(body, option_title,
          range: { price: { lte: @max_price }})
      end if @option_titles

      add_post_filters(body,
        range: { price: { lte: @max_price }})

    end

    if params[:q].present?
      body.deep_merge!({
        query: {
          bool: {
            must: {
              match: {title: params[:q]}
            }
          }
        }
      })
    end

    page = params.fetch(:page, '1').to_i - 1
    result = $client.search({index: 'farm', body: body, size: PER_PAGE, from: page * PER_PAGE})

    @category_ids_buckets = result['aggregations']['category_ids']['category_ids']['buckets']
    @option_buckets = {}
    @option_titles.each do |option_title|
      @option_buckets[option_title] = result['aggregations'][option_title][option_title]['buckets']
    end if @option_titles
    @min_price_range = result['aggregations']['min_price']
    @max_price_range = result['aggregations']['max_price']

    @products = Kaminari.paginate_array(result['hits']['hits'], total_count: result['hits']['total']).page(params[:page]).per(PER_PAGE)

    respond_to do |format|
      format.html
      format.js
    end

  end

  private

  def add_filters_for_aggregations(body, aggregation_name, condition)
    body[:aggregations][aggregation_name][:filter] ||= {}
    body[:aggregations][aggregation_name][:filter][:bool] ||= {}
    body[:aggregations][aggregation_name][:filter][:bool][:must] ||= []
    body[:aggregations][aggregation_name][:filter][:bool][:must] << condition
  end

  def add_post_filters(body, condition)
    body[:filter] ||= {}
    body[:filter][:bool] ||= {}
    body[:filter][:bool][:must] ||= []
    body[:filter][:bool][:must] << condition
  end

  def store_location
    session[:previous_url] = request.fullpath
  end

  def store_category_id
    session[:category_id] = @category.id if @category
  end

end

app/controllers/farm/welcome_controller.rb
class Farm::WelcomeController < Farm::ApplicationController

  def index
    @categories = categories_root.children

    body = {
      aggregations: {
        "animal_ids": {
          terms: {
            field: "properties.animal_ids"
          }
        }
      }
    }

    result = $client.search({index: 'farm', body: body, size: 0})
    buckets = result['aggregations']['animal_ids']['buckets']

    @animals = Tree.find(buckets.map{|bucket| bucket['key']}).
      map{|animal| [
        animal,
        buckets.find{|bucket| bucket['key'] == animal.id}['doc_count']]}

  end

end

app/views/farm/search/_search_filters.html.erb
<div class="search-filters-inside m-t-3 m-b-3">
  <div class="m-b-3">
    <h5>Категория</h5>
    <%= categories_tree(categories_root.hash_tree) %>
  </div>

  <% @option_titles.each do |option_title| %>
    <div class="m-b-1">
      <%= option_filter option_title %>
    </div>
  <% end if @option_titles %>

  <div class="m-b-1">
    <h5>Цена</h5>
    <%= text_field_tag :min_price, @min_price, data: {"price-param": params[:min_price], "price-range": @min_price_range['min_price']['value'].to_i}, class: 'js-filter-control js-filter-text-input js-filter-price form-control form-control-sm min-price-input' %>
    -
    <%= text_field_tag :max_price, @max_price, data: {"price-param": params[:max_price], "price-range": @max_price_range['max_price']['value'].to_i}, class: 'js-filter-control js-filter-text-input js-filter-price form-control form-control-sm max-price-input' %>
    <div class="price-slider m-t-1"></div>
  </div>
</div>

app/views/farm/search/_search_products.html.erb
<%= render 'title' %>

<div class="card-deck-wrapper">
  <% products_per_slice = 3 %>

  <% @products.each_slice(products_per_slice).with_index do |slice, index| %>

    <% if index == 1 %>
      <div class="card-deck">
        <div class="card text-xs-center">
          <div class="card-block">
            <h3 class="card-title">Фермерский магазин в подмосковье</h3>
            <p class="cart-text">Бесплатная доставка в радиусе 20 км при покупке от 2000 руб.</p>
            <%= link_to "Подробнее", farm_about_path, class: "btn btn-outline-primary" %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="card-deck">
      <% slice.each do |product| %>
        <div class="card product__card">
          <div class="product__hovered">
            <% if farm_product_in_cart?(product['_id']) %>
              <%= link_to 'Товар в корзине', farm_cart_path, class: 'product__add-to-basket btn btn-warning' %>
            <% else %>
              <%= link_to "в корзину", farm_cart_path(product_id: product['_id']), class: "js-add-to-cart-button product__add-to-basket btn btn-outline-success", data: {id: product['_id']}, remote: true, method: :post %>
            <% end %>
          </div>
          <%= link_to farm_product_path(product['_id']), class: 'product__link' do %>
            <% if product['_source']['images'] %>
              <%= image_tag product['_source']['images'].first['small'], class: "card-img-top img-fluid", alt: product['_source']['title'] %>
            <% else %>
              <img class="card-img-top" data-src="holder.js/100px170/thumb" alt="Card image cap">
            <% end %>
            <div class="card-block">
              <p class="product__title card-title"><%= product['_source']['title'] %></p>
              <p class="card-text" style="font-size: .8rem">
                <%= number_to_currency product['_source']['price'] %>
                за 1
                <%= product['_source']['unit'] %>.
              </p>
            </div>
          <% end %>
        </div>
      <% end %>
      <% (products_per_slice - slice.size).times do |space| %>
        <div class="card" style="visibility: hidden"></div>
      <% end %>
    </div>
  <% end %>
</div>

<%= paginate @products, window: 2 %>

app/views/farm/search/_title.html.erb
<h2 class="m-b-2">
  <% if @category && !@category.root? %>
    <%= @meta_title = @category.es_body['title'] %>
  <% else %>
    <%= @meta_title = 'Все товары' %>
  <% end %>
</h2>

<div class="m-b-2" style="line-height: 2rem">
  <% @option_values.keys.each do |key| %>
    <% concat " " %>
    <% @option_values[key].map do |value| 
      concat " "
      option_ids = request.query_parameters[key].reject{|el| el == value.id.to_s}
      concat(
        link_to(request.query_parameters.merge(key => option_ids), class: "btn-delete-aggregation") do
          concat value.es_body['title']
          concat " "
          concat icon("times-circle")
        end
      )
      concat " и " if @option_values[key].size > 1 && @option_values[key].last != value
    end %>
  <% end if @option_values %>

  <% if params[:min_price] || params[:max_price] %>
    стоимостью 
    <% if params[:min_price] %>
      <%= link_to request.query_parameters.except(:min_price), class: "btn-delete-aggregation" do %>
        от <%= number_to_currency params[:min_price], precision: 0 %>
        <%= icon "times-circle" %>
      <% end %>
    <% end %>

    <% if params[:max_price] %>
      <%= link_to request.query_parameters.except(:max_price), class: "btn-delete-aggregation" do %>
        до <%= number_to_currency params[:max_price], precision: 0 %>
        <%= icon "times-circle" %>
      <% end %>
    <% end %>
  <% end %>

  <% if params[:q].present? %>
    <%= link_to request.query_parameters.except(:q), class: "btn-delete-aggregation" do %>
      по запросу
      "<%= params[:q] %>"
      <%= icon "times-circle" %>
    <% end %>
  <% end %>

</div>

app/views/farm/search/index.html.erb
<%= container do %>
  <%= row do %>
    <div class="col-xl-2"></div>
    <div class="search-filters col-xs-13 col-lg-5 col-xl-4 col-md-24 tether-width">
      <%= render 'farm/search/search_filters' %>
    </div>
    <div class="search-products col-xs-24 col-xl-16 col-lg-19 col-md-24">
      <%= render 'farm/search/search_products' %>
    </div>
  <% end %>
<% end %>

app/views/farm/search/index.js.erb
{
  "search-filters": "<%= j render "farm/search/search_filters" %>",
  "filter-popup-hint": "<%= j link_to "Найдено #{@products.total_count} #{t 'product', count: @products.total_count}", request.query_parameters %> "
}