config/routes.rb
Rails.application.routes.draw do

  constraints domain: 'podychevo.ru' do
    scope module: 'farm', as: 'farm' do
      get 'about', to: 'about#show'
      resource :order, only: [:create]
      resource :cart, only: [:show, :update, :create]
      get 'search(/page/:page)', to: 'search#index', as: 'search'
      resources :products, only: [:show]
      root 'welcome#index'
    end
  end

  constraints host: '192.168.1.6', port: '3000' do
    resources :trees
    resources :products
    resources :uploads
    root 'products#index'
  end

end

app/models/product.rb
class Product < ApplicationRecord
  #store :properties, accessors: [ :color, :voltage ]#, coder: JSON
  after_save :store_in_es

  def store_in_es
    self.update_column :es_response, $client.index(index: es_index, type: es_type, id: id, body: es_body)
  end

  def self.reindex!
    Product.all.each do |p|
      p.store_in_es
    end
    true
  end

end

app/controllers/farm/_animals_controller.rb
class Farm::AnimalsController < Farm::ApplicationController

  PER_PAGE = 15

  def show
    @animal = animals_root.children.where("es_body ->> 'title' = ?", params[:id]).first

    body = {
      aggregations: {
        category_ids: {
          terms: {
            field: "category_ids"
          }
        },
        animal_ids: {
          terms: {
            field: "animal_ids"
          }
        }
      },
      query: {
        bool: {
          filter: {
            term: {
              animal_ids: @animal.id
            }
          }
        }
      }
    }

    page = params.fetch(:page, '1').to_i - 1
    result = $client.search({index: 'farm', body: body, size: PER_PAGE, from: page * PER_PAGE})

    @category_ids_buckets = result['aggregations']['category_ids']['buckets']
    @animal_ids_buckets = result['aggregations']['animal_ids']['buckets']

    @products = Kaminari.paginate_array(result['hits']['hits'], total_count: result['hits']['total']).page(params[:page]).per(PER_PAGE)
    render 'search/index'
  end
end

app/controllers/farm/_categories_controller.rb
#class Farm::CategoriesController < Farm::ApplicationController
#
#  PER_PAGE = 15
#  TREE_INDEX = 'farm'
#  TREE_TYPE = 'categories'
#
#  def show
#    @category = categories_root.children.where("es_body ->> 'title' = ?", params[:id]).first
#
#    body = {
#      aggregations: {
#        category_ids: {
#          terms: {
#            field: "category_ids"
#          }
#        },
#        animal_ids: {
#          filter: {
#            term: {
#              category_ids: @category.id
#            }
#          },
#          aggregations: {
#            animal_ids: {
#              terms: {
#                field: "animal_ids"
#              }
#            }
#          }
#        }
#      },
#      filter: {
#        term: {
#          category_ids: @category.id
#        }
#      }
#    }
#
#    if params[:title].present?
#      body.deep_merge!({
#        query: {
#          bool: {
#            must: {
#              match: {title: params[:title]}
#            }
#          }
#        }
#      })
#    end
#
#    page = params.fetch(:page, '1').to_i - 1
#    result = $client.search({index: 'farm', body: body, size: PER_PAGE, from: page * PER_PAGE})
#
#    @category_ids_buckets = result['aggregations']['category_ids']['buckets']
#    @animal_ids_buckets = result['aggregations']['animal_ids']['animal_ids']['buckets']
#
#    @products = Kaminari.paginate_array(result['hits']['hits'], total_count: result['hits']['total']).page(params[:page]).per(PER_PAGE)
#    render 'search/index'
#  end
#end

app/controllers/farm/about_controller.rb
class Farm::AboutController < Farm::ApplicationController
end

app/controllers/farm/application_controller.rb
class Farm::ApplicationController < ApplicationController
  prepend_view_path 'app/views/farm'
  helper_method :categories_root, :options_root, :farm_products_in_cart, :farm_product_in_cart?, :farm_total_cost_of_products_in_cart

  private
  
  def categories_root
    Tree.roots.where(es_index: 'farm', es_type: 'category_ids').first
  end

  def options_root(option_title)
    Tree.roots.where(es_index: 'farm', es_type: option_title).first
  end

  def farm_products
    Product.where(es_index: 'farm', es_type: 'products')
  end

  def farm_products_in_cart
    if session['cart_product_hashes']
      farm_products.where(id: session['cart_product_hashes'].keys)
    else
      farm_products.none
    end
  end

  def farm_product_in_cart?(id)
    session[:cart_product_hashes] && session[:cart_product_hashes].key?(id.to_s)
  end

  def farm_total_cost_of_products_in_cart
    farm_products_in_cart.sum do |product|
      product.es_body['price'] * session['cart_product_hashes'][product.id.to_s]
    end
  end

end

app/controllers/farm/carts_controller.rb
class Farm::CartsController < Farm::ApplicationController
  def create
    product_id = params[:product_id]
    (session['cart_product_hashes'] ||= {}).tap do |cph|
      if cph.key? product_id
        cph[product_id] += 1
      else
        cph[product_id] = 1
      end
    end
  end

  def update

    product_id = params[:product_id]
    count = params[:count].to_i

    if count <= 0
      session['cart_product_hashes'].delete(product_id)
    else
      session['cart_product_hashes'][product_id] = count
      @sum =  params[:count].to_i * Product.find(product_id).es_body['price']
      @products = farm_products_in_cart
    end

    respond_to do |format|
      format.json
    end

  end

  def show
    @products = farm_products_in_cart
    @order = Farm::Order.new
    if @products.exists?
      render 'show'
    else
      render 'empty'
    end
  end

end

app/controllers/farm/orders_controller.rb
class Farm::OrdersController < Farm::ApplicationController

  def create
    @order = Farm::Order.new(order_params)
    if @order.valid?
      @products = farm_products_in_cart
      @session_hash = session.to_hash
      @farm_total_cost_of_products_in_cart = farm_total_cost_of_products_in_cart
      Farm::SellerMailer.order_email(@products, @order, @session_hash, @farm_total_cost_of_products_in_cart).deliver_now
      Farm::BuyerMailer.order_email(@products, @order, @session_hash, @farm_total_cost_of_products_in_cart).deliver_now
      respond_to do |format|
        format.js {render 'create_success'}
      end
      session.delete 'cart_product_hashes'
    else 
      respond_to do |format|
        format.js {render 'create_fail'}
      end
    end
  end

  private

  def order_params
    params.require(:farm_order).permit(:name, :phone, :address, :email)
  end

end

app/controllers/farm/products_controller.rb
class Farm::ProductsController < Farm::ApplicationController

  before_action :history_routines

  def show

    @product = Product.find(params[:id])

    fill_breadcrumbs()

    #if @product.es_body['animal_ids']
    #  @animals = animals_root.children.find(@product.es_body['animal_ids'])
    #end

    body = {
      aggregations: {
        category_ids: {
          terms: {
            field: "category_ids",
            size: 100
          }
        }
      }
    }

    result = $client.search({index: 'farm', body: body})
    @category_ids_buckets = result['aggregations']['category_ids']['buckets']
  end

  private

  def history_routines
    session['history_product_ids'] ||= []
    session['history_product_ids'] |= [params[:id]]
    session['history_product_ids'] = session['history_product_ids'].last(30)
    @history_products = farm_products.where(id: session['history_product_ids'])
  end

  def fill_breadcrumbs
    category_ids = @product.es_body['category_ids']
    @breadcrumbs = []
    leaves = Tree.leaves.with_ancestor(categories_root).where(id: @product.es_body['category_ids'])
    leaves.each do |leaf|
      @breadcrumbs << leaf.self_and_ancestors.reverse_order
    end

    if session[:category_id]
      @breadcrumbs.each_with_index do |breadcrumb, index|
        if breadcrumb.map{|b| b.id}.include? session[:category_id]
          primary = @breadcrumbs.delete_at(index)
          @breadcrumbs.unshift primary
          break
        end
      end
    end
  end
end

app/controllers/farm/search_controller.rb
class Farm::SearchController < Farm::ApplicationController

  before_action :store_location

  PER_PAGE = 18

  def index

    if params[:category_id]
      @category = Tree.find(params[:category_id])
    else
      @category = categories_root
    end

    store_category_id()

    @option_titles = @category.es_body['options']

    if @option_titles
      @option_values = {}
      @option_titles.each do |option_title|
        if params[option_title]
          @option_values[option_title] = Tree.find(params[option_title])
        end
      end
    end

    if params[:min_price]
      @min_price = params[:min_price].to_i
    end

    if params[:max_price]
      @max_price = params[:max_price].to_i
    end

    body = {
      aggregations: {
        max_price: {
          filter: {},
          aggregations: {
            max_price: {
              max: { 
                field: "price" 
              }
            }
          }
        },
        min_price: {
          filter: {},
          aggregations: {
            min_price: {
              min: { 
                field: "price" 
              }
            }
          }
        },
        category_ids: {
          filter: {},
          aggregations: {
            category_ids: {
              terms: {
                field: "category_ids",
                size: 100
              }
            }
          }
        }
      }
    }

    @option_titles.each do |option_title|
      body[:aggregations][option_title] = {
        filter: {},
        aggregations: {
          option_title => {
            terms: {
              field: "properties.#{option_title}",
              size: 100
            }
          }
        }
      }
    end if @option_titles

    @option_titles.each do |option_title|

      if @option_values[option_title]

        add_filters_for_aggregations(body, :category_ids,
          terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })

        add_filters_for_aggregations(body, :min_price,
          terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })

        add_filters_for_aggregations(body, :max_price,
          terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })

        other_option_titles = @option_titles - [option_title]

        other_option_titles.each do |other_option_title|
          add_filters_for_aggregations(body, other_option_title,
            terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })
        end if other_option_titles

        add_post_filters(body,
          terms: { "properties.#{option_title}" => @option_values[option_title].map(&:id) })

      end


    end if @option_titles

    if @category

      add_filters_for_aggregations(body, :min_price,
        term: { category_ids: @category.id })

      add_filters_for_aggregations(body, :max_price,
        term: { category_ids: @category.id })

      @option_titles.each do |option_title|
        add_filters_for_aggregations(body, option_title,
          term: { category_ids: @category.id })
      end if @option_titles

      add_post_filters(body,
        term: { category_ids: @category.id })
    end

    if @min_price

      add_filters_for_aggregations(body, :category_ids,
        range: { price: { gte: @min_price }})

      @option_titles.each do |option_title|
        add_filters_for_aggregations(body, option_title,
          range: { price: { gte: @min_price }})
      end if @option_titles

      add_post_filters(body,
        range: { price: { gte: @min_price }})
    end

    if @max_price

      add_filters_for_aggregations(body, :category_ids,
        range: { price: { lte: @max_price }})

      @option_titles.each do |option_title|
        add_filters_for_aggregations(body, option_title,
          range: { price: { lte: @max_price }})
      end if @option_titles

      add_post_filters(body,
        range: { price: { lte: @max_price }})

    end

    if params[:q].present?
      body.deep_merge!({
        query: {
          bool: {
            must: {
              match: {title: params[:q]}
            }
          }
        }
      })
    end

    page = params.fetch(:page, '1').to_i - 1
    result = $client.search({index: 'farm', body: body, size: PER_PAGE, from: page * PER_PAGE})

    @category_ids_buckets = result['aggregations']['category_ids']['category_ids']['buckets']
    @option_buckets = {}
    @option_titles.each do |option_title|
      @option_buckets[option_title] = result['aggregations'][option_title][option_title]['buckets']
    end if @option_titles
    @min_price_range = result['aggregations']['min_price']
    @max_price_range = result['aggregations']['max_price']

    @products = Kaminari.paginate_array(result['hits']['hits'], total_count: result['hits']['total']).page(params[:page]).per(PER_PAGE)

    respond_to do |format|
      format.html
      format.js
    end

  end

  private

  def add_filters_for_aggregations(body, aggregation_name, condition)
    body[:aggregations][aggregation_name][:filter] ||= {}
    body[:aggregations][aggregation_name][:filter][:bool] ||= {}
    body[:aggregations][aggregation_name][:filter][:bool][:must] ||= []
    body[:aggregations][aggregation_name][:filter][:bool][:must] << condition
  end

  def add_post_filters(body, condition)
    body[:filter] ||= {}
    body[:filter][:bool] ||= {}
    body[:filter][:bool][:must] ||= []
    body[:filter][:bool][:must] << condition
  end

  def store_location
    session[:previous_url] = request.fullpath
  end

  def store_category_id
    session[:category_id] = @category.id if @category
  end

end

app/controllers/farm/welcome_controller.rb
class Farm::WelcomeController < Farm::ApplicationController

  def index
    @categories = categories_root.children

    body = {
      aggregations: {
        "animal_ids": {
          terms: {
            field: "properties.animal_ids"
          }
        }
      }
    }

    result = $client.search({index: 'farm', body: body, size: 0})
    buckets = result['aggregations']['animal_ids']['buckets']

    @animals = Tree.find(buckets.map{|bucket| bucket['key']}).
      map{|animal| [
        animal,
        buckets.find{|bucket| bucket['key'] == animal.id}['doc_count']]}

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.page params[:page]
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      # TODO!
      params.require(:product).permit!#(:properties)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/farm/products/_breadcrumb.html.erb
<nav class="breadcrumb m-b-1">
  <%= link_to 'Магазин', farm_search_path, class: 'breadcrumb-item' %>
  <% (primary = @breadcrumbs.shift).each_with_index do |element, index| %>
    <% next if index == 0 %>
    <%= link_to element.es_body['title'], farm_search_path(category_id: element.id), class: 'breadcrumb-item' %>
  <% end %>

  <% if session[:previous_url] %>
    <%= link_to session[:previous_url], id: 'back-breadcrumb', class: 'breadcrumb-item pull-xs-right' do %>
      <%= icon 'caret-left' %>
      Назад
    <% end %>
  <% end %>
</nav>

<% if @breadcrumbs.present? %>
  <div style="font-size: 90%" class="m-b-1 clearfix">
    <span class="pull-xs-left">
      Товар так же находится в категории:
    </span>
      <% @breadcrumbs.each_with_index do |breadcrumb, index| %>
        <nav class="breadcrumb pull-xs-left m-l-1" style="margin: 0; padding: 0; background: none">
          <% (secondary = breadcrumb).each_with_index do |element, index| %>
            <% next if index == 0 %>
            <%= link_to element.es_body['title'], farm_search_path(category_id: element.id), class: 'breadcrumb-item' %>
          <% end %>
          <%= content_tag(:span, ' и ', class: 'm-l-1')  if breadcrumb != @breadcrumbs.last %> 
        </nav>
      <% end %>
  </div>
<% end %>

app/views/farm/products/show.html.erb
<%= container do %>
  <%= row do %>
    <div class="col-xl-2"></div>
    <div class="col-xs-24 col-lg-24 col-xl-20">

      <%= row do %>
        <h2 class="m-b-2"><%= @meta_title = @product.es_body['title'] %></h2>

        <%= render 'farm/products/breadcrumb' %>

        <%= row do %>
          <div class="col-xs-24 col-xl-16 col-lg-17 vcenter">
            <div style="padding: 0 4rem;">
              <div class="slider slider-for">
                <% if @product.es_body['images'] %>
                  <% @product.es_body['images'].each do |image| %>
                    <%= content_tag :div, class: 'tmp' do %>
                      <%= image_tag(image['big'], class: 'img-fluid', style: 'max-height: 470px', class: 'm-x-auto photo img-fluid')  %>
                    <% end %>
                  <% end %>
                <% else %>
                  <%= content_tag :div, class: 'tmp' do %>
                    <%= image_tag('not_available.png', class: 'img-fluid', style: 'max-height: 470px', class: 'm-x-auto photo img-fluid')  %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div><!--
          --><div class="col-xs-24 col-xl-8 col-lg-7 vcenter">
            <div>
              <small class="text-success">
                <%= icon 'check' %>
                Товар в наличии
              </small>
              <h5 class="m-t-0"><%= number_to_currency @product.es_body['price'] %></h5>
              <div>
                <% if farm_product_in_cart? @product.id %>
                  <%= link_to 'Товар в корзине', farm_cart_path, class: 'btn btn-warning m-t-2 m-b-1' %>
                <% else %>
                  <%= link_to farm_cart_path(product_id: @product), class: "js-add-to-cart-button btn btn-success m-t-2 m-b-1", data: {id: @product.id}, remote: true, method: :post do %>
                    <%= icon 'cart-arrow-down m-r-1' %>Добавить в корзину
                  <% end %>
                <% end %>
              </div>

              <div>
                <button type="button" class="btn btn-sm btn-secondary">Задать вопрос</button>
              </div>
              <div class="m-y-2">
                <% if @product.es_body['images'] && @product.es_body['images'].size > 1 %>
                  <strong class="text-muted m-y-1">Другие фото товара</strong>
                  <div class="slider slider-nav m-y-1">
                    <% @product.es_body['images'].each do |image| %>
                      <%= content_tag :div do %>
                        <%= image_tag image['small'], class: 'img-fluid' %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>

              <div class="m-y-2">
              <%= link_to 'Редактировать товар', edit_product_url(@product) %>
              </div>

            </div>
          </div>
        <% end %>

      <% end %>

      <%= row style: 'border-top: 1rem solid #FAFAFA;', class: 'p-t-3 m-b-3' do %>
        <div class="col-xs-24">
          <% @product.es_body['properties'].each do |key, values| %>
            <p><%= options_root(key).children.find(values).map{|v| v.es_body['title']} %></p>
          <% end %>
        </div>
      <% end %>

      <%= row style: 'border-top: 1rem solid #FAFAFA;', class: 'p-t-3 m-b-3' do %>
        <div class="col-xs-24">
          <h4> Возможно вас так же заинтересует </h4>
          aaa
        </div>
      <% end %>

      <%= row style: "border-top: 1rem solid #FAFAFA;", class: 'p-t-3 m-b-3' do %>
        <div class="col-lg-24">
          <h4> Ранее вы просматривали </h4>
          <% @history_products.each do |history_product| %>
            <div><%= history_product %></div>
          <% end %>
        </div>
      <% end %>

    </div>
  <% end %>
<% end %>